// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDBni0xaIYi7qt3u5XdkOjRS2p0JAYeo',
    appId: '1:536287924777:web:3ae2479728c41cf3c0c238',
    messagingSenderId: '536287924777',
    projectId: 'depi-project-1dda8',
    authDomain: 'depi-project-1dda8.firebaseapp.com',
    storageBucket: 'depi-project-1dda8.firebasestorage.app',
    measurementId: 'G-H2X46H7NLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeracAMFlbOyrX1vrIUpID2qwKXa_IfOU',
    appId: '1:536287924777:android:a9d0f015b00e9dbac0c238',
    messagingSenderId: '536287924777',
    projectId: 'depi-project-1dda8',
    storageBucket: 'depi-project-1dda8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnLLucdBf8kkxarm51qQyoReQLU0P_rEU',
    appId: '1:536287924777:ios:0742c9ef1fa072f8c0c238',
    messagingSenderId: '536287924777',
    projectId: 'depi-project-1dda8',
    storageBucket: 'depi-project-1dda8.firebasestorage.app',
    iosBundleId: 'com.example.depiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnLLucdBf8kkxarm51qQyoReQLU0P_rEU',
    appId: '1:536287924777:ios:0742c9ef1fa072f8c0c238',
    messagingSenderId: '536287924777',
    projectId: 'depi-project-1dda8',
    storageBucket: 'depi-project-1dda8.firebasestorage.app',
    iosBundleId: 'com.example.depiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHDBni0xaIYi7qt3u5XdkOjRS2p0JAYeo',
    appId: '1:536287924777:web:64c510d4f7dfe2ffc0c238',
    messagingSenderId: '536287924777',
    projectId: 'depi-project-1dda8',
    authDomain: 'depi-project-1dda8.firebaseapp.com',
    storageBucket: 'depi-project-1dda8.firebasestorage.app',
    measurementId: 'G-GWLCX3J1C4',
  );
}
